### ISSUE TITLE
Meta-Considerations For Issues & Discussions

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [AFg6K7h4fhy2/Genetic-Evolution-Tournament#1]
## Goal

Add checklist of issues & discussions that should be created to facilitate tournament development. 

## Context

Presently, the Genetic Evolution Tournament has been developed privately by the author. Many questions are not yet _fully_ written, and there remains considerable "editing" work that, while not a crux to the project (as in this work doesn't quite need to be done), would be nice to have done. This editing might include community feedback on existing and yet uncompleted sections, both before and after the tournament is live. The following checklist will help to make sure issues and discussions critical to the tournament's success are covered. 

## Tasks

- [ ] Tournament Front Matter (discussion & issue)
- [ ] Questions (discussions & issue)
- [ ] Announcement (discussion & issue)
- [ ] Impact & Success Measures (discussion & issue)
- [ ] Fortified Essay (issue)
- [ ] Feedback & Outreach (discussion & issue)
- [ ] Visualizations (discussion & issue)
- [ ] Appendix (discussion & issue)
- [ ] Resources (discussion & issue)

## Not Covered In This Issue

- This issue does not cover the content of the checklist items
- Completion of this issue is not dependent upon completion of the checklist items

## Resources & Links

None.
