### ISSUE TITLE
Tracker For Launch-Question Batches

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [AFg6K7h4fhy2/Genetic-Evolution-Tournament#45]
This issue covers tracking progress on batches of 10 questions for each of the five question categories of this tournament.

* Each question batch issue is marked complete when a first-pass (reviewed by one person) of the each component question has been given. 
* Resource: [types of Metaculus questions](https://www.metaculus.com/questions/create/)
* Resource: [question writing guide, Metaculus](https://www.metaculus.com/question-writing/)
* Rather than go ELSI01 &rarr; ELSI02 ..., the author has decided ELSI01 &rarr; TACA01 seems more sensible. 

Checklist:

* [ ] Ethical, Legal, and Societal Implications (ELSI)
  * [ ] ELSI Questions Batch 01
  * [ ] ELSI Questions Batch 02
  * [ ] ELSI Questions Batch 03
* [ ] Technological Advancements and Clinical Applications (TACA)
  * [ ] TACA Questions Batch 01
  * [ ] TACA Questions Batch 02
  * [ ] TACA Questions Batch 03
* [ ] Regulatory and Policy Developments (RPD)
  * [ ] RPD Questions Batch 01
  * [ ] RPD Questions Batch 02
  * [ ] RPD Questions Batch 03
* [ ] Accessibility and Demographic Shifts (ADS)
  * [ ] ADS Questions Batch 01
  * [ ] ADS Questions Batch 02
  * [ ] ADS Questions Batch 03
* [ ] Healthcare and Insurance System Evolution (HISE)
  * [ ] HISE Questions Batch 01
  * [ ] HISE Questions Batch 02
  * [ ] HISE Questions Batch 03

**Comment by AFg6K7h4fhy2** [comment]
Below are the intended completion dates. 

* P1: Pass One, The question title has been written and vetted once.
* P2: Pass Two, The question background, resolution criteria, and fine print are written.
* P3: Pass Three, The P2 content has been reviewed.

The question categories:

* Ethical, Legal, and Societal Implications (ELSI)
  * ELSI Questions Batch 01 (P1, P2: December 22)
  * ELSI Questions Batch 02 (P1: December 22; P2: December 29)
  * ELSI Questions Batch 03 (P1: December 29; P2: January 7)
* Technological Advancements and Clinical Applications (TACA)
  * TACA Questions Batch 01 (P1, P2: December 22)
  * TACA Questions Batch 02 (P1: December 22; P2: December 29)
  * TACA Questions Batch 03 (P1: December 29; P2: January 7)
* Regulatory and Policy Developments (RPD)
  * RPD Questions Batch 01 (P1, P2: December 22)
  * RPD Questions Batch 02 (P1: December 22; P2: December 29)
  * RPD Questions Batch 03 (P1: January 7; P2: January 15)
* Accessibility and Demographic Shifts (ADS)
  * ADS Questions Batch 01 (P1, P2: December 22)
  * ADS Questions Batch 02 (P1: December 29; P2: January 7)
  * ADS Questions Batch 03 (P1: January 7; P2: January 15)
* Healthcare and Insurance System Evolution (HISE)
  * HISE Questions Batch 01 (P1: December 22; P2: December 29)
  * HISE Questions Batch 02 (P1: December 29; P2: January 7)
  * HISE Questions Batch 03 (P1: January 7; P2: January 15)

**Comment by AFg6K7h4fhy2** [comment]
The question batches will take into account suggestions made as of 2024-12-22 by external researchers.

**Comment by AFg6K7h4fhy2** [comment]
In the Introductions for each question group, there can be several checklists illustrating or summarizing the nature of the contained questions. For example, in Ethical, Legal, and Societal Implications (ELSI), there can be a table of questions by category (i.e. number of question by their membership to the topics ethics, legality, and societal-implications).

**Comment by AFg6K7h4fhy2** [comment]
Societal implications should likely be changes to milestones for humanity, since demographic shifts seems very close to "societal implications".
